### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by scottlamb** [wutchzone/rust-vmaf#1]
Thanks for taking the effort to create this wrapper!

Looks like there's no license declared on it—no license file in the repo, no license declared in `Cargo.toml`. Would you be willing to add one? fwiw, dual Apache 2.0 / MIT is common as mentioned here: https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive

**Comment by wutchzone** [comment]
Sure, added the license in the [recent commit](https://github.com/wutchzone/rust-vmaf/commit/35519d7973193958e9f0d01dab8ebc3de971e105). Thank you for your feedback!
